# Decision Table Data - Auto-generated from DecisionTable.xlsx
# Total rows: 244

DECISION_DATA = [
    {
        'MarkaId': 4,
        'AltKategoriId': 102,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 5.87,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1581,
        'AlimFiyat_USD': 28.75,
        'Sarf': 1.96
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 102,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 13990,
        'KumasHedefMaliyet': 10.26,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2765,
        'AlimFiyat_USD': 50.27,
        'Sarf': 1.96
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 102,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 17990,
        'KumasHedefMaliyet': 13.19,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 3555,
        'AlimFiyat_USD': 64.64,
        'Sarf': 1.96
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 102,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.6,
        'SegmentPSF': 14990,
        'KumasHedefMaliyet': 10.99,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2962,
        'AlimFiyat_USD': 53.85,
        'Sarf': 1.96
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 1699,
        'KumasHedefMaliyet': 2.64,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 515,
        'AlimFiyat_USD': 9.36,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 2.68,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 523,
        'AlimFiyat_USD': 9.51,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 3.64,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 5.06,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 988,
        'AlimFiyat_USD': 17.96,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 6.07,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 4.05,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 5.06,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 988,
        'AlimFiyat_USD': 17.96,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 7.08,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 8.1,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1581,
        'AlimFiyat_USD': 28.75,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 2,
        'LifeStyleGrupId': 8,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 3.64,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 57,
        'SegmentId': 3,
        'LifeStyleGrupId': 8,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 4.66,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.42
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 6.46,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1394,
        'AlimFiyat_USD': 25.35,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 6.31,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1363,
        'AlimFiyat_USD': 24.78,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 6.87,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1484,
        'AlimFiyat_USD': 26.98,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.16,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 6.87,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1484,
        'AlimFiyat_USD': 26.98,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 8.59,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1855,
        'AlimFiyat_USD': 33.73,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 13990,
        'KumasHedefMaliyet': 12.03,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2596,
        'AlimFiyat_USD': 47.2,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 1,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.16,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 3,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 8.59,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1855,
        'AlimFiyat_USD': 33.73,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 54,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 11.16,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2410,
        'AlimFiyat_USD': 43.82,
        'Sarf': 1.57
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 5.44,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1212,
        'AlimFiyat_USD': 22.04,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 5.1,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1136,
        'AlimFiyat_USD': 20.65,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 8.33,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1855,
        'AlimFiyat_USD': 33.73,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 4.16,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 927,
        'AlimFiyat_USD': 16.85,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 5.83,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 6.66,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1484,
        'AlimFiyat_USD': 26.98,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 8.33,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1855,
        'AlimFiyat_USD': 33.73,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 13990,
        'KumasHedefMaliyet': 11.65,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2596,
        'AlimFiyat_USD': 47.2,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 2,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 5.83,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 56,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 8.33,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1855,
        'AlimFiyat_USD': 33.73,
        'Sarf': 1.62
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 6.07,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 5.69,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 853,
        'AlimFiyat_USD': 15.51,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 4.46,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 668,
        'AlimFiyat_USD': 12.15,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 6.18,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 927,
        'AlimFiyat_USD': 16.85,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 7.43,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 8.67,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 11.14,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1670,
        'AlimFiyat_USD': 30.36,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 1,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 4.95,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 742,
        'AlimFiyat_USD': 13.49,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 2,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 5.69,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 853,
        'AlimFiyat_USD': 15.51,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 3,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 7.43,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 43,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 8.67,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 1.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 2.96,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 606,
        'AlimFiyat_USD': 11.02,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 2.55,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 523,
        'AlimFiyat_USD': 9.51,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 3.26,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 668,
        'AlimFiyat_USD': 12.15,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 4.52,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 927,
        'AlimFiyat_USD': 16.85,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.34,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 7.24,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1484,
        'AlimFiyat_USD': 26.98,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 3.62,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 742,
        'AlimFiyat_USD': 13.49,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 4.52,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 927,
        'AlimFiyat_USD': 16.85,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.34,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.34,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 58,
        'SegmentId': 5,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 11.76,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2410,
        'AlimFiyat_USD': 43.82,
        'Sarf': 1.49
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 44,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 454,
        'AlimFiyat_USD': 8.25,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 44,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 853,
        'AlimFiyat_USD': 15.51,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 44,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 44,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 44,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 44,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 49,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 8.43,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2424,
        'AlimFiyat_USD': 44.07,
        'Sarf': 2.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 49,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 13990,
        'KumasHedefMaliyet': 9.03,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2596,
        'AlimFiyat_USD': 47.2,
        'Sarf': 2.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 49,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 14990,
        'KumasHedefMaliyet': 9.68,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2781,
        'AlimFiyat_USD': 50.56,
        'Sarf': 2.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 49,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 22990,
        'KumasHedefMaliyet': 14.84,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 4265,
        'AlimFiyat_USD': 77.55,
        'Sarf': 2.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 49,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 8.39,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2410,
        'AlimFiyat_USD': 43.82,
        'Sarf': 2.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 49,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 14990,
        'KumasHedefMaliyet': 9.68,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2781,
        'AlimFiyat_USD': 50.56,
        'Sarf': 2.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 49,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 22990,
        'KumasHedefMaliyet': 14.84,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 4265,
        'AlimFiyat_USD': 77.55,
        'Sarf': 2.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 49,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 22990,
        'KumasHedefMaliyet': 14.84,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 4265,
        'AlimFiyat_USD': 77.55,
        'Sarf': 2.09
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.67,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1818,
        'AlimFiyat_USD': 33.05,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 4.97,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1591,
        'AlimFiyat_USD': 28.93,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 5.1,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 5.01,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1604,
        'AlimFiyat_USD': 29.16,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 5.1,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 7.23,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2316,
        'AlimFiyat_USD': 42.11,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 5.1,
        'SegmentPSF': 15990,
        'KumasHedefMaliyet': 8.9,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2850,
        'AlimFiyat_USD': 51.82,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 5.1,
        'SegmentPSF': 22990,
        'KumasHedefMaliyet': 12.79,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 4098,
        'AlimFiyat_USD': 74.51,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 5.1,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 5.01,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1604,
        'AlimFiyat_USD': 29.16,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 5.1,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 7.23,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2316,
        'AlimFiyat_USD': 42.11,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 5.1,
        'SegmentPSF': 15990,
        'KumasHedefMaliyet': 8.9,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2850,
        'AlimFiyat_USD': 51.82,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 5.1,
        'SegmentPSF': 22990,
        'KumasHedefMaliyet': 12.79,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 4098,
        'AlimFiyat_USD': 74.51,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 5.1,
        'SegmentPSF': 15990,
        'KumasHedefMaliyet': 8.9,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2850,
        'AlimFiyat_USD': 51.82,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 51,
        'SegmentId': 5,
        'LifeStyleGrupId': 8,
        'MU': 5.1,
        'SegmentPSF': 22990,
        'KumasHedefMaliyet': 12.79,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 4098,
        'AlimFiyat_USD': 74.51,
        'Sarf': 2.33
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 3.24,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 606,
        'AlimFiyat_USD': 11.02,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.3,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 4.07,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 761,
        'AlimFiyat_USD': 13.84,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.3,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 5.65,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1057,
        'AlimFiyat_USD': 19.22,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.3,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 7.91,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1480,
        'AlimFiyat_USD': 26.91,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.3,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 4.52,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 845,
        'AlimFiyat_USD': 15.36,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.3,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 5.65,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1057,
        'AlimFiyat_USD': 19.22,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.3,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 7.91,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1480,
        'AlimFiyat_USD': 26.91,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.3,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 9.04,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1691,
        'AlimFiyat_USD': 30.75,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 3,
        'LifeStyleGrupId': 8,
        'MU': 4.3,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 6.78,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1268,
        'AlimFiyat_USD': 23.05,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.3,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 7.91,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1480,
        'AlimFiyat_USD': 26.91,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 47,
        'SegmentId': 5,
        'LifeStyleGrupId': 8,
        'MU': 4.3,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 9.04,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1691,
        'AlimFiyat_USD': 30.75,
        'Sarf': 1.36
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 53,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.45,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2121,
        'AlimFiyat_USD': 38.56,
        'Sarf': 2.39
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 53,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 5.08,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1670,
        'AlimFiyat_USD': 30.36,
        'Sarf': 2.39
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 53,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 7.33,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2410,
        'AlimFiyat_USD': 43.82,
        'Sarf': 2.39
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 53,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 7.33,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2410,
        'AlimFiyat_USD': 43.82,
        'Sarf': 2.39
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 53,
        'SegmentId': 3,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 5.65,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1855,
        'AlimFiyat_USD': 33.73,
        'Sarf': 2.39
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 84,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 3.84,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 818,
        'AlimFiyat_USD': 14.87,
        'Sarf': 1.55
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 84,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.22,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 1.55
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 84,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.1,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1299,
        'AlimFiyat_USD': 23.62,
        'Sarf': 1.55
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 84,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 6.96,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1484,
        'AlimFiyat_USD': 26.98,
        'Sarf': 1.55
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 84,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 4.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 853,
        'AlimFiyat_USD': 15.51,
        'Sarf': 1.55
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 84,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.22,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 1.55
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 899,
        'KumasHedefMaliyet': 2.54,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 272,
        'AlimFiyat_USD': 4.95,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 1299,
        'KumasHedefMaliyet': 2.75,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 295,
        'AlimFiyat_USD': 5.36,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 1799,
        'KumasHedefMaliyet': 3.11,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 334,
        'AlimFiyat_USD': 6.07,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 3.98,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 427,
        'AlimFiyat_USD': 7.76,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 2999,
        'KumasHedefMaliyet': 5.18,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 556,
        'AlimFiyat_USD': 10.11,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 7.95,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 853,
        'AlimFiyat_USD': 15.51,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 3.46,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 371,
        'AlimFiyat_USD': 6.75,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 3.98,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 427,
        'AlimFiyat_USD': 7.76,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 2999,
        'KumasHedefMaliyet': 5.18,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 556,
        'AlimFiyat_USD': 10.11,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 6.92,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 742,
        'AlimFiyat_USD': 13.49,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 3,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 3.98,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 427,
        'AlimFiyat_USD': 7.76,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 60,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 2999,
        'KumasHedefMaliyet': 5.18,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 556,
        'AlimFiyat_USD': 10.11,
        'Sarf': 0.78
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 606,
        'AlimFiyat_USD': 11.02,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 523,
        'AlimFiyat_USD': 9.51,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 668,
        'AlimFiyat_USD': 12.15,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 853,
        'AlimFiyat_USD': 15.51,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 4.9,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1855,
        'AlimFiyat_USD': 33.73,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 427,
        'AlimFiyat_USD': 7.76,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 742,
        'AlimFiyat_USD': 13.49,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 853,
        'AlimFiyat_USD': 15.51,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1670,
        'AlimFiyat_USD': 30.36,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 2,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 668,
        'AlimFiyat_USD': 12.15,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 3,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 853,
        'AlimFiyat_USD': 15.51,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 61,
        'SegmentId': 4,
        'LifeStyleGrupId': 8,
        'MU': 4.9,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1113,
        'AlimFiyat_USD': 20.24,
        'Sarf': 0.0
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 82,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 5.96,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1484,
        'AlimFiyat_USD': 26.98,
        'Sarf': 1.81
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 82,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 9.68,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2410,
        'AlimFiyat_USD': 43.82,
        'Sarf': 1.81
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 55,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 17.13,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1484,
        'AlimFiyat_USD': 26.98,
        'Sarf': 0.63
    },
    {
        'MarkaId': 4,
        'AltKategoriId': 55,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.9,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 19.28,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1670,
        'AlimFiyat_USD': 30.36,
        'Sarf': 0.63
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 102,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 5.13,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 1.96
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 102,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 5.87,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1581,
        'AlimFiyat_USD': 28.75,
        'Sarf': 1.96
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 102,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 6.6,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1778,
        'AlimFiyat_USD': 32.33,
        'Sarf': 1.96
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 102,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 9.52,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2567,
        'AlimFiyat_USD': 46.67,
        'Sarf': 1.96
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 57,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 2.68,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 523,
        'AlimFiyat_USD': 9.51,
        'Sarf': 1.42
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 57,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 2.32,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 454,
        'AlimFiyat_USD': 8.25,
        'Sarf': 1.42
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 57,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 3.9965406904416794,
        'SegmentPSF': 2999,
        'KumasHedefMaliyet': 3.49,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 682,
        'AlimFiyat_USD': 12.4,
        'Sarf': 1.42
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 57,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 4.66,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.42
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 57,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 6.07,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 1.42
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 54,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 5.26,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1136,
        'AlimFiyat_USD': 20.65,
        'Sarf': 1.57
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 54,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.41,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 1.57
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 54,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 7.32,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1581,
        'AlimFiyat_USD': 28.75,
        'Sarf': 1.57
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 54,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 9.15,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1976,
        'AlimFiyat_USD': 35.93,
        'Sarf': 1.57
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 54,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 13990,
        'KumasHedefMaliyet': 12.81,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2765,
        'AlimFiyat_USD': 50.27,
        'Sarf': 1.57
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 56,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 2999,
        'KumasHedefMaliyet': 3.06,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 682,
        'AlimFiyat_USD': 12.4,
        'Sarf': 1.62
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 56,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 4.43,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 988,
        'AlimFiyat_USD': 17.96,
        'Sarf': 1.62
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 56,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 3.55,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 1.62
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 56,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 4.43,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 988,
        'AlimFiyat_USD': 17.96,
        'Sarf': 1.62
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 56,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.21,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 1.62
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 56,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 7.1,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1581,
        'AlimFiyat_USD': 28.75,
        'Sarf': 1.62
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 56,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 8.87,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1976,
        'AlimFiyat_USD': 35.93,
        'Sarf': 1.62
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 43,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 5.27,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 1.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 43,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 6.07,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 43,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 4.74,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 1.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 43,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 5.27,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 1.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 43,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 6.07,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 43,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 7.91,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 1.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 43,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 9.23,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 1.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 1699,
        'KumasHedefMaliyet': 2.51,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 515,
        'AlimFiyat_USD': 9.36,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 2.21,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 454,
        'AlimFiyat_USD': 8.25,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 3.47,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 4.44,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 4.82,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 988,
        'AlimFiyat_USD': 17.96,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.75,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 3.47,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 4.44,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 58,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.79,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 1.49
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 44,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 1799,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 409,
        'AlimFiyat_USD': 7.44,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 44,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 44,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 44,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 44,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 44,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 44,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 49,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 8.93,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2567,
        'AlimFiyat_USD': 46.67,
        'Sarf': 2.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 49,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 13990,
        'KumasHedefMaliyet': 9.62,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2765,
        'AlimFiyat_USD': 50.27,
        'Sarf': 2.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 49,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 6.19,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1778,
        'AlimFiyat_USD': 32.33,
        'Sarf': 2.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 49,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 6.88,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1976,
        'AlimFiyat_USD': 35.93,
        'Sarf': 2.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 49,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 8.93,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2567,
        'AlimFiyat_USD': 46.67,
        'Sarf': 2.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 49,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 14990,
        'KumasHedefMaliyet': 10.31,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2962,
        'AlimFiyat_USD': 53.85,
        'Sarf': 2.09
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 4.73,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1515,
        'AlimFiyat_USD': 27.55,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.8,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 5.32,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1704,
        'AlimFiyat_USD': 30.98,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.8,
        'SegmentPSF': 9999,
        'KumasHedefMaliyet': 5.91,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1894,
        'AlimFiyat_USD': 34.44,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.8,
        'SegmentPSF': 14990,
        'KumasHedefMaliyet': 8.86,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2839,
        'AlimFiyat_USD': 51.62,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 4.8,
        'SegmentPSF': 15990,
        'KumasHedefMaliyet': 9.45,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 3028,
        'AlimFiyat_USD': 55.05,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.8,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 4.14,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1326,
        'AlimFiyat_USD': 24.11,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.8,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 5.32,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1704,
        'AlimFiyat_USD': 30.98,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.8,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 7.68,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2460,
        'AlimFiyat_USD': 44.73,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.8,
        'SegmentPSF': 13990,
        'KumasHedefMaliyet': 8.27,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2650,
        'AlimFiyat_USD': 48.18,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 51,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.8,
        'SegmentPSF': 15990,
        'KumasHedefMaliyet': 9.45,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 3028,
        'AlimFiyat_USD': 55.05,
        'Sarf': 2.33
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 3.24,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 606,
        'AlimFiyat_USD': 11.02,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 2.8,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 523,
        'AlimFiyat_USD': 9.51,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.2,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 4.16,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 779,
        'AlimFiyat_USD': 14.16,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.2,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 5.32,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 995,
        'AlimFiyat_USD': 18.09,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.2,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 6.94,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1298,
        'AlimFiyat_USD': 23.6,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.2,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 4.63,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 866,
        'AlimFiyat_USD': 15.75,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.2,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 5.32,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 995,
        'AlimFiyat_USD': 18.09,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.2,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 6.94,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1298,
        'AlimFiyat_USD': 23.6,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 47,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.2,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 8.1,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1515,
        'AlimFiyat_USD': 27.55,
        'Sarf': 1.36
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 53,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 4.81,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1581,
        'AlimFiyat_USD': 28.75,
        'Sarf': 2.39
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 53,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 8999,
        'KumasHedefMaliyet': 5.41,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1778,
        'AlimFiyat_USD': 32.33,
        'Sarf': 2.39
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 53,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 12990,
        'KumasHedefMaliyet': 7.81,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 2567,
        'AlimFiyat_USD': 46.67,
        'Sarf': 2.39
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 83,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 83,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 2999,
        'KumasHedefMaliyet': 3.2,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 682,
        'AlimFiyat_USD': 12.4,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 3.71,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 4.27,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.56,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 3.34,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 3.71,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 4.27,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 5.56,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 84,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 6.49,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 1.55
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 799,
        'KumasHedefMaliyet': 2.26,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 242,
        'AlimFiyat_USD': 4.4,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 899,
        'KumasHedefMaliyet': 1.9,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 204,
        'AlimFiyat_USD': 3.71,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 1199,
        'KumasHedefMaliyet': 2.21,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 237,
        'AlimFiyat_USD': 4.31,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 3.68,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 395,
        'AlimFiyat_USD': 7.18,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 2599,
        'KumasHedefMaliyet': 4.79,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 514,
        'AlimFiyat_USD': 9.35,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 5,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 6.63,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 1499,
        'KumasHedefMaliyet': 2.76,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 296,
        'AlimFiyat_USD': 5.38,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 1999,
        'KumasHedefMaliyet': 3.68,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 395,
        'AlimFiyat_USD': 7.18,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 2999,
        'KumasHedefMaliyet': 5.53,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 593,
        'AlimFiyat_USD': 10.78,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 60,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 7.36,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 0.78
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 1,
        'LifeStyleGrupId': 2,
        'MU': 3.0,
        'SegmentPSF': 1799,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 545,
        'AlimFiyat_USD': 9.91,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 1,
        'LifeStyleGrupId': 1,
        'MU': 4.0,
        'SegmentPSF': 1799,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 409,
        'AlimFiyat_USD': 7.44,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 2,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 3,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 3999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 790,
        'AlimFiyat_USD': 14.36,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 4,
        'LifeStyleGrupId': 1,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 2299,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 454,
        'AlimFiyat_USD': 8.25,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 3599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 711,
        'AlimFiyat_USD': 12.93,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4599,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 909,
        'AlimFiyat_USD': 16.53,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 4,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 5999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1186,
        'AlimFiyat_USD': 21.56,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 61,
        'SegmentId': 5,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 0.0,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 0.0
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 82,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 3.97,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 988,
        'AlimFiyat_USD': 17.96,
        'Sarf': 1.81
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 82,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 5.56,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 1.81
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 55,
        'SegmentId': 1,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 4999,
        'KumasHedefMaliyet': 11.4,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 988,
        'AlimFiyat_USD': 17.96,
        'Sarf': 0.63
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 55,
        'SegmentId': 2,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 6999,
        'KumasHedefMaliyet': 15.97,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1383,
        'AlimFiyat_USD': 25.15,
        'Sarf': 0.63
    },
    {
        'MarkaId': 8,
        'AltKategoriId': 55,
        'SegmentId': 3,
        'LifeStyleGrupId': 3,
        'MU': 4.6,
        'SegmentPSF': 7999,
        'KumasHedefMaliyet': 18.25,
        'HesaplamaKuru': 55,
        'KDV': 0.1,
        'AlimFiyat_TRY': 1581,
        'AlimFiyat_USD': 28.75,
        'Sarf': 0.63
    },
]


def find_decision_values(MarkaId, AltKategoriId, SegmentId, LifeStyleGrupId):
    """
    Find decision table values based on input parameters
    
    Args:
        MarkaId (int): Brand ID
        AltKategoriId (int): Sub-category ID
        SegmentId (int): Segment ID (UDF5)
        LifeStyleGrupId (int): LifeStyle Group ID
        
    Returns:
        dict: Decision table values with all output fields
    """
    
    for row in DECISION_DATA:
        if (row["MarkaId"] == MarkaId and
            row["AltKategoriId"] == AltKategoriId and
            row["SegmentId"] == SegmentId and
            row["LifeStyleGrupId"] == LifeStyleGrupId):
            
            return {
                "MU": row["MU"],
                "SegmentPSF": row["SegmentPSF"],
                "KumasHedefMaliyet": row["KumasHedefMaliyet"],
                "HesaplamaKuru": row["HesaplamaKuru"],
                "KDV": row["KDV"],
                "AlimFiyat_TRY": row["AlimFiyat_TRY"],
                "AlimFiyat_USD": row["AlimFiyat_USD"],
                "Sarf": row["Sarf"]
            }
    
    # If no match found, return all zeros
    return {
        "MU": 0,
        "SegmentPSF": 0,
        "KumasHedefMaliyet": 0,
        "HesaplamaKuru": 0,
        "KDV": 0,
        "AlimFiyat_TRY": 0,
        "AlimFiyat_USD": 0,
        "Sarf": 0
    }


# Example usage for PLM:
# result = find_decision_values(MarkaId=4, AltKategoriId=102, SegmentId=2, LifeStyleGrupId=1)
# print(result)
# Output: {"MU": 4.6, "SegmentPSF": 7999, "KumasHedefMaliyet": 5.87, ..., "Sarf": 1.96}